export type Language = "sv" | "en";

export const LANGUAGE_COOKIE = "flyttiva-language";

export const ui = {
  sv: {
    brandHome: "Flyttiva startsida",
    brandTagline: "Flytt med omtanke.",
    nav: { services: "Tjänster", process: "Så fungerar det", faq: "FAQ", plan: "Planera din flytt", main: "Huvudmeny", mobile: "Mobilmeny", open: "Öppna meny", close: "Stäng meny" },
    language: "Välj språk",
    footer: { about: "Professionell flytthjälp, utförd med omsorg.", chat: "Skicka en bokningsförfrågan", rights: "Alla rättigheter förbehållna.", label: "Sidfot", services: "Tjänster", pricing: "Priser", contact: "Kontakt" },
    home: {
      heroTitle: "Flytthjälp utan krångel.", heroText: "Vi hjälper privatpersoner och företag att flytta tryggt, effektivt och utan onödig stress — i hela Sverige.", heroAlt: "Flyttkartonger i ett ljust, modernt hem",
      servicesKicker: "Våra tjänster", servicesTitle: <>Allt du behöver.<br /> <em>Inget du inte gör.</em></>, servicesText: "Välj det som passar din flytt. Vi hjälper dig att forma resten i ett enkelt samtal.", allServices: "Se alla tjänster", quote: "Be om offert", askAbout: "Fråga om",
      processKicker: "Så fungerar det", processTitle: <>Tre steg.<br /> <em>En lugn flytt.</em></>, processText: "Du berättar vad du behöver. Vi löser planeringen, logistiken och det praktiska.",
      steps: [{title:"Skicka en förfrågan",text:"Fyll i adresser, önskat datum och bostadsstorlek i vårt enkla formulär."},{title:"Få en tydlig plan",text:"Vi återkommer med upplägg, pris och allt som ingår — utan överraskningar."},{title:"Vi flyttar",text:"Vårt team kommer i tid och tar hand om flytten från start till mål."}],
      trustKicker: "Trygghet ingår", trustTitle: <>Du flyttar livet.<br /> <em>Vi flyttar resten.</em></>, trustText: "En bra flytt märks inte i stressen — den märks i lugnet. Därför får du en tydlig kontakt, varsam hantering och full överblick hela vägen.", trustAlt: "Flyttivas team bär en flyttlåda", badge: "omsorg i varje steg", checks: ["Dina ägodelar är försäkrade", "Punktligt och erfaret team", "Tydligt pris före flyttdagen"], testimonial: "“Otroligt proffsiga, snabba och varsamma. Hela flytten kändes enkel från första kontakt.”", cite: "— Anna, Stockholm",
      faqKicker:"Bra att veta", faqTitle:<>Vanliga frågor,<br /> <em>enkla svar.</em></>, faqText:"Undrar du något annat? Skriv direkt till oss så hjälper vi dig.", askQuestion:"Ställ en fråga",
      ctaKicker:"Redo när du är", ctaTitle:<>Låt oss göra flytten<br /> <em>lite lättare.</em></>, ctaText:"Fyra uppgifter räcker för att komma igång: från, till, datum och bostadsstorlek.", ctaButton:"Skicka en förfrågan",
      labels:["Hem","Företag","Komplett"]
    },
    servicesPage:{metaTitle:"Tjänster",metaDescription:"Omsorgsfull flytthjälp för hem och företag — från packning till flyttstädning.",kicker:"Tjänster",title:<>Flytthjälp,<br /> <em>på ditt sätt.</em></>,text:"Välj en komplett lösning eller bara den hjälp du behöver. Vi anpassar team, tid och upplägg efter din flytt.",ask:"Fråga om tjänsten",ctaKicker:"Personlig planering",ctaTitle:<>Osäker på vad<br /> <em>du behöver?</em></>,ctaText:"Beskriv flytten i formuläret. Vi hjälper dig hitta rätt upplägg.",ctaButton:"Öppna bokningsformuläret"},
    pricing:{metaTitle:"Priser",metaDescription:"Tydlig och personlig prissättning för din flytt — utan dolda kostnader.",kicker:"Prissättning",title:<>Tydligt från<br /> <em>första stund.</em></>,text:"Ingen flytt är den andra lik. Därför får du ett personligt pris baserat på det du faktiskt behöver — alltid tydligt före bokning.",button:"Be om ett pris",factorsKicker:"Vad avgör priset?",factorsTitle:<>Rätt pris för<br /> <em>just din flytt.</em></>,factorsText:"Skicka fyra korta uppgifter så kan vi snabbt förstå uppdraget och ge dig ett transparent förslag.",factors:[{title:"Omfattning",text:"Bostadsstorlek, mängd och vilka tjänster du vill ha hjälp med."},{title:"Förutsättningar",text:"Avstånd, våningsplan, hiss och åtkomst vid båda adresserna."},{title:"Tidpunkt",text:"Önskat datum, veckodag och hur flexibel planeringen kan vara."}],promiseKicker:"Vårt löfte",promiseTitle:<>Inga paket.<br /> <em>Inga överraskningar.</em></>,promiseText:"Du får en tydlig offert anpassad efter din verkliga flytt, inte ett standardpaket fyllt med sådant du inte behöver.",checks:["Kostnadsfri förfrågan","Tydligt vad som ingår","Personlig kontakt före bokning"],ctaKicker:"Få din offert",ctaTitle:<>Fyra uppgifter.<br /> <em>Ett tydligt pris.</em></>,ctaText:"Berätta varifrån, vart, när och hur stort. Vi återkommer så snart vi kan.",ctaButton:"Skicka en förfrågan"},
    contact:{metaTitle:"Kontakt",metaDescription:"Kontakta Flyttiva via bokningsformuläret eller telefon.",kicker:"Kontakt",title:<>Vi är bara ett<br /> <em>meddelande bort.</em></>,text:"Berätta kort om flytten i formuläret så hjälper vi dig vidare. Du kan också ringa oss under våra öppettider.",button:"Öppna bokningsformuläret",fast:"Enklast",bookingOptionTitle:"Bokningsförfrågan",chatText:"Skicka alla flyttdetaljer på en gång",call:"Ring oss",weekdays:"Vardagar 08:00–18:00",hours:"Öppettider",hoursText:<>Måndag–fredag 08:00–18:00<br />Lördag–söndag 10:00–16:00</>,moves:<>Flyttar utförs alla dagar<br />efter överenskommelse.</>},
    booking:{button:"Boka din flytt",eyebrow:"Bokningsförfrågan",title:"Berätta om din flytt",intro:"Fyll i detaljerna nedan så återkommer vi med ett tydligt upplägg och pris.",close:"Stäng bokningsformuläret",name:"Namn",namePlaceholder:"Ditt fullständiga namn",phone:"Telefonnummer",email:"E-post",emailPlaceholder:"namn@exempel.se",from:"Från",to:"Till",address:"Adress",addressPlaceholder:"Gatuadress, postnummer och ort",floor:"Våning",fromFloorPlaceholder:"T.ex. 3 eller BV",toFloorPlaceholder:"T.ex. 2 eller BV",elevator:"Finns hiss?",choose:"Välj",yes:"Ja",no:"Nej",description:"Beskrivning",descriptionPlaceholder:"Berätta gärna om bostadsstorlek, önskat datum, tunga föremål eller annat vi behöver känna till.",note:"Ingen bindande bokning. Vi bekräftar upplägg och pris med dig först.",submit:"Skicka förfrågan",submitting:"Skickar…",successTitle:"Tack — vi har fått din förfrågan.",successText:"Vi går igenom detaljerna och återkommer så snart vi kan.",referenceLabel:"Referens",closeSuccess:"Klart",errors:{validation:"Kontrollera att alla obligatoriska uppgifter är korrekt ifyllda.",configuration:"Formuläret är inte helt konfigurerat ännu. Ring oss gärna under tiden.",delivery:"Något gick fel när förfrågan skickades. Försök igen eller ring oss."}}
  },
  en: {
    brandHome: "Flyttiva home",
    brandTagline: "Moving, considered.",
    nav: { services: "Services", process: "How it works", faq: "FAQ", plan: "Plan your move", main: "Main menu", mobile: "Mobile menu", open: "Open menu", close: "Close menu" },
    language: "Choose language",
    footer: { about: "Professional moving help, handled with care.", chat: "Send a booking enquiry", rights: "All rights reserved.", label: "Footer", services: "Services", pricing: "Pricing", contact: "Contact" },
    home: {
      heroTitle: "Moving help without the hassle.", heroText: "We help individuals and businesses move safely, efficiently and without unnecessary stress — across Sweden.", heroAlt: "Moving boxes in a bright, modern home",
      servicesKicker: "Our services", servicesTitle: <>Everything you need.<br /> <em>Nothing you don’t.</em></>, servicesText: "Choose what suits your move. We’ll shape the rest with you in one simple conversation.", allServices: "View all services", quote: "Request a quote", askAbout: "Ask about",
      processKicker: "How it works", processTitle: <>Three steps.<br /> <em>One calm move.</em></>, processText: "Tell us what you need. We handle the planning, logistics and practical details.",
      steps: [{title:"Send an enquiry",text:"Add your addresses, preferred date and home size in our simple form."},{title:"Get a clear plan",text:"We’ll reply with the plan, price and everything included — no surprises."},{title:"We move you",text:"Our team arrives on time and handles your move from start to finish."}],
      trustKicker: "Peace of mind included", trustTitle: <>You move your life.<br /> <em>We move the rest.</em></>, trustText: "A good move is not defined by stress, but by calm. You get one clear point of contact, careful handling and complete visibility throughout.", trustAlt: "The Flyttiva team carrying a moving box", badge: "care at every step", checks: ["Your belongings are insured", "Punctual, experienced team", "Clear price before moving day"], testimonial: "“Incredibly professional, fast and careful. The whole move felt easy from the very first contact.”", cite: "— Anna, Stockholm",
      faqKicker:"Good to know", faqTitle:<>Common questions,<br /> <em>simple answers.</em></>, faqText:"Wondering about something else? Message us and we’ll be happy to help.", askQuestion:"Ask a question",
      ctaKicker:"Ready when you are", ctaTitle:<>Let’s make moving<br /> <em>a little easier.</em></>, ctaText:"Four details are enough to get started: from, to, date and home size.", ctaButton:"Send an enquiry",
      labels:["Home","Business","Complete"]
    },
    servicesPage:{metaTitle:"Services",metaDescription:"Careful moving help for homes and businesses — from packing to move-out cleaning.",kicker:"Services",title:<>Moving help,<br /> <em>your way.</em></>,text:"Choose a complete solution or only the help you need. We adapt the team, timing and plan to your move.",ask:"Ask about this service",ctaKicker:"Personal planning",ctaTitle:<>Not sure what<br /> <em>you need?</em></>,ctaText:"Describe your move in the form. We’ll help you find the right setup.",ctaButton:"Open the booking form"},
    pricing:{metaTitle:"Pricing",metaDescription:"Clear, personal pricing for your move — with no hidden costs.",kicker:"Pricing",title:<>Clear from<br /> <em>the very start.</em></>,text:"No two moves are alike. You receive a personal price based on what you actually need — always clear before booking.",button:"Request a price",factorsKicker:"What determines the price?",factorsTitle:<>The right price for<br /> <em>your move.</em></>,factorsText:"Send four short details and we can quickly understand the job and give you a transparent proposal.",factors:[{title:"Scope",text:"Home size, volume and the services you would like help with."},{title:"Conditions",text:"Distance, floors, lifts and access at both addresses."},{title:"Timing",text:"Preferred date, day of the week and how flexible the planning can be."}],promiseKicker:"Our promise",promiseTitle:<>No packages.<br /> <em>No surprises.</em></>,promiseText:"You receive a clear quote tailored to your actual move, not a standard package filled with things you do not need.",checks:["Free enquiry","Clear list of what is included","Personal contact before booking"],ctaKicker:"Get your quote",ctaTitle:<>Four details.<br /> <em>One clear price.</em></>,ctaText:"Tell us where from, where to, when and how much. We’ll get back to you as soon as we can.",ctaButton:"Send an enquiry"},
    contact:{metaTitle:"Contact",metaDescription:"Contact Flyttiva through the booking form or by phone.",kicker:"Contact",title:<>We’re only a<br /> <em>message away.</em></>,text:"Tell us briefly about your move in the form and we’ll help you from there. You can also call during opening hours.",button:"Open the booking form",fast:"Easiest",bookingOptionTitle:"Booking enquiry",chatText:"Send every moving detail in one go",call:"Call us",weekdays:"Weekdays 08:00–18:00",hours:"Opening hours",hoursText:<>Monday–Friday 08:00–18:00<br />Saturday–Sunday 10:00–16:00</>,moves:<>Moves are carried out every day<br />by arrangement.</>},
    booking:{button:"Book your move",eyebrow:"Booking enquiry",title:"Tell us about your move",intro:"Fill in the details below and we’ll return with a clear plan and price.",close:"Close booking form",name:"Name",namePlaceholder:"Your full name",phone:"Phone number",email:"Email",emailPlaceholder:"name@example.com",from:"From",to:"To",address:"Address",addressPlaceholder:"Street address, postcode and city",floor:"Floor",fromFloorPlaceholder:"E.g. 3 or ground floor",toFloorPlaceholder:"E.g. 2 or ground floor",elevator:"Is there a lift?",choose:"Choose",yes:"Yes",no:"No",description:"Description",descriptionPlaceholder:"Tell us about the home size, preferred date, heavy items or anything else we should know.",note:"This is not a binding booking. We confirm the plan and price with you first.",submit:"Send enquiry",submitting:"Sending…",successTitle:"Thank you — we received your enquiry.",successText:"We’ll review the details and get back to you as soon as we can.",referenceLabel:"Reference",closeSuccess:"Done",errors:{validation:"Check that every required field is filled in correctly.",configuration:"The form is not fully configured yet. Please call us in the meantime.",delivery:"Something went wrong while sending your enquiry. Try again or call us."}}
  }
} as const;

export function getUi(language: Language) {
  return ui[language];
}
